[package]
name = "slime-token"
version = "1.0.0"
authors = []

[addresses]
slime= "_"
deployer = "_"
[dev-addresses]

[dependencies]
AptosFramework = { local = "../framework/aptos-framework" }
AptosTokenObjects = { local = "../framework/aptos-token-objects" }
[dev-dependencies]
